### ISSUE TITLE
Cannot compile gdev with current boost

### ISSUE THREAD

**Issue by kozross** [CPFL/gdev#1]
When I try to compile this code following the instructions given here, I get errors. These are just the first few - the actual error dump is _much_ longer:

/home/koz/gdev/cuda/runtime/ocelot/analysis/implementation/ControlTree.cpp: In member function ‘bool analysis::ControlTree::_interact(const NodeVector&, const NodeVector&)’:
/home/koz/gdev/cuda/runtime/ocelot/analysis/implementation/ControlTree.cpp:872:21: error: use of deleted function ‘void boost::ref(const T&&) [with T = analysis::ControlTree_]’
      boost::ref(this), _1, _2));
                     ^
In file included from /usr/include/boost/ref.hpp:15:0,
                 from /usr/include/boost/bind/bind.hpp:25,
                 from /usr/include/boost/bind.hpp:22,
                 from /home/koz/gdev/cuda/runtime/ocelot/analysis/implementation/ControlTree.cpp:22:
/usr/include/boost/core/ref.hpp:174:24: note: declared here
 template<class T> void ref(T const&&) BOOST_REF_DELETE;
                        ^
/home/koz/gdev/cuda/runtime/ocelot/analysis/implementation/ControlTree.cpp:878:21: error: use of deleted function ‘void boost::ref(const T&&) [with T = analysis::ControlTree_]’
      boost::ref(this), _1, _2));
                     ^
In file included from /usr/include/boost/ref.hpp:15:0,
                 from /usr/include/boost/bind/bind.hpp:25,
                 from /usr/include/boost/bind.hpp:22,
                 from /home/koz/gdev/cuda/runtime/ocelot/analysis/implementation/ControlTree.cpp:22:
/usr/include/boost/core/ref.hpp:174:24: note: declared here
 template<class T> void ref(T const&&) BOOST_REF_DELETE;
                        ^
/home/koz/gdev/cuda/runtime/ocelot/analysis/implementation/ControlTree.cpp:884:21: error: use of deleted function ‘void boost::ref(const T&&) [with T = analysis::ControlTree*]’
      boost::ref(this), _1, _2));
                     ^
In file included from /usr/include/boost/ref.hpp:15:0,
                 from /usr/include/boost/bind/bind.hpp:25,
                 from /usr/include/boost/bind.hpp:22,
                 from /home/koz/gdev/cuda/runtime/ocelot/analysis/implementation/ControlTree.cpp:22:
/usr/include/boost/core/ref.hpp:174:24: note: declared here
 template<class T> void ref(T const&&) BOOST_REF_DELETE;

**Comment by Ultra-Seven** [comment]
Have you solved this problem? I encountered the same one..  orz

**Comment by Ultra-Seven** [comment]
boost 1.50 can fix this problem

**Comment by Constellation** [comment]
Fixed it with 7bd129f393df0f628c33b048fd1b275fa9bb0885. Thanks :)
